// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CVm9HP1HSzEihU8JEFiF7cd_mo0j5tE',
    appId: '1:110215447027:web:8845beba5e05064181d286',
    messagingSenderId: '110215447027',
    projectId: 'hello-flutter-e6bd7',
    authDomain: 'hello-flutter-e6bd7.firebaseapp.com',
    storageBucket: 'hello-flutter-e6bd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbEiGkxCWrkCheEaQT30DkGG8k1ukYI8',
    appId: '1:110215447027:android:b8d7a0137fce68e681d286',
    messagingSenderId: '110215447027',
    projectId: 'hello-flutter-e6bd7',
    storageBucket: 'hello-flutter-e6bd7.appspot.com',
  );
}
